package Ynzc.Util;

public class TwMobilelocation {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column tw_MobileLocation.AutoCde
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    private String autocde;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column tw_MobileLocation.MoblieBegin
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    private String mobliebegin;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column tw_MobileLocation.MoblieEnd
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    private String moblieend;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column tw_MobileLocation.Province
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    private String province;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column tw_MobileLocation.City
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    private String city;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column tw_MobileLocation.AreaCode
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    private String areacode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column tw_MobileLocation.PostCode
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    private String postcode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column tw_MobileLocation.Corp
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    private String corp;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column tw_MobileLocation.Card
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    private String card;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column tw_MobileLocation.AutoCde
     *
     * @return the value of tw_MobileLocation.AutoCde
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public String getAutocde() {
        return autocde;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column tw_MobileLocation.AutoCde
     *
     * @param autocde the value for tw_MobileLocation.AutoCde
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public void setAutocde(String autocde) {
        this.autocde = autocde;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column tw_MobileLocation.MoblieBegin
     *
     * @return the value of tw_MobileLocation.MoblieBegin
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public String getMobliebegin() {
        return mobliebegin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column tw_MobileLocation.MoblieBegin
     *
     * @param mobliebegin the value for tw_MobileLocation.MoblieBegin
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public void setMobliebegin(String mobliebegin) {
        this.mobliebegin = mobliebegin;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column tw_MobileLocation.MoblieEnd
     *
     * @return the value of tw_MobileLocation.MoblieEnd
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public String getMoblieend() {
        return moblieend;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column tw_MobileLocation.MoblieEnd
     *
     * @param moblieend the value for tw_MobileLocation.MoblieEnd
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public void setMoblieend(String moblieend) {
        this.moblieend = moblieend;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column tw_MobileLocation.Province
     *
     * @return the value of tw_MobileLocation.Province
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column tw_MobileLocation.Province
     *
     * @param province the value for tw_MobileLocation.Province
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column tw_MobileLocation.City
     *
     * @return the value of tw_MobileLocation.City
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column tw_MobileLocation.City
     *
     * @param city the value for tw_MobileLocation.City
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column tw_MobileLocation.AreaCode
     *
     * @return the value of tw_MobileLocation.AreaCode
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column tw_MobileLocation.AreaCode
     *
     * @param areacode the value for tw_MobileLocation.AreaCode
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column tw_MobileLocation.PostCode
     *
     * @return the value of tw_MobileLocation.PostCode
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column tw_MobileLocation.PostCode
     *
     * @param postcode the value for tw_MobileLocation.PostCode
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column tw_MobileLocation.Corp
     *
     * @return the value of tw_MobileLocation.Corp
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public String getCorp() {
        return corp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column tw_MobileLocation.Corp
     *
     * @param corp the value for tw_MobileLocation.Corp
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public void setCorp(String corp) {
        this.corp = corp;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column tw_MobileLocation.Card
     *
     * @return the value of tw_MobileLocation.Card
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column tw_MobileLocation.Card
     *
     * @param card the value for tw_MobileLocation.Card
     *
     * @abatorgenerated Sun Jun 27 17:38:59 CST 2010
     */
    public void setCard(String card) {
        this.card = card;
    }
}